
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_kriteria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kriteria.IPDelReKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kriteria.OPDelRefKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kriteria.IPGetRefKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kriteria.OPGetRefKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kriteria.IPInsRefKritereia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kriteria.OPInsRefKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kriteria.IPUpdRefKriteria;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kriteria.OPUpdRefKriteria;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KRITERIA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kriteria.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kriteria.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kriteria.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kriteria.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kriteria.OPGetRefKriteria
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kriteria", partName = "part_get_reply")
    public OPGetRefKriteria get(
        @WebParam(name = "IPGetRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kriteria", partName = "part_get_request")
        IPGetRefKriteria partGetRequest);

    /**
     * 
     * @param insertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kriteria.OPInsRefKriteria
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kriteria", partName = "insert_reply")
    public OPInsRefKriteria insert(
        @WebParam(name = "IPInsRefKritereia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kriteria", partName = "insert_request")
        IPInsRefKritereia insertRequest);

    /**
     * 
     * @param updateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kriteria.OPUpdRefKriteria
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kriteria", partName = "part_update_reply")
    public OPUpdRefKriteria update(
        @WebParam(name = "IPUpdRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kriteria", partName = "update_request")
        IPUpdRefKriteria updateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kriteria.OPDelRefKriteria
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kriteria", partName = "part_delete_reply")
    public OPDelRefKriteria delete(
        @WebParam(name = "IPDelReKriteria", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kriteria", partName = "part_delete_request")
        IPDelReKriteria partDeleteRequest);

}
