
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_kriteria;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_MASTER_REF_KRITERIA", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KRITERIA", wsdlLocation = "http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_KRITERIA?WSDL")
public class WSMASTERREFKRITERIA
    extends Service
{

    private final static URL WSMASTERREFKRITERIA_WSDL_LOCATION;
    private final static WebServiceException WSMASTERREFKRITERIA_EXCEPTION;
    private final static QName WSMASTERREFKRITERIA_QNAME = new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KRITERIA", "WS_MASTER_REF_KRITERIA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_KRITERIA?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMASTERREFKRITERIA_WSDL_LOCATION = url;
        WSMASTERREFKRITERIA_EXCEPTION = e;
    }

    public WSMASTERREFKRITERIA() {
        super(__getWsdlLocation(), WSMASTERREFKRITERIA_QNAME);
    }

    public WSMASTERREFKRITERIA(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMASTERREFKRITERIA_QNAME, features);
    }

    public WSMASTERREFKRITERIA(URL wsdlLocation) {
        super(wsdlLocation, WSMASTERREFKRITERIA_QNAME);
    }

    public WSMASTERREFKRITERIA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMASTERREFKRITERIA_QNAME, features);
    }

    public WSMASTERREFKRITERIA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMASTERREFKRITERIA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt() {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KRITERIA", "execute_pt"), ExecutePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KRITERIA", "execute_pt"), ExecutePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMASTERREFKRITERIA_EXCEPTION!= null) {
            throw WSMASTERREFKRITERIA_EXCEPTION;
        }
        return WSMASTERREFKRITERIA_WSDL_LOCATION;
    }

}
