
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_kbli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kbli.IPDelRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kbli.OPDelRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kbli.IPGetRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kbli.OPGetRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kbli.IPInsRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kbli.OPInsRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kbli.IPUpdRefKbli;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kbli.OPUpdRefKbli;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KBLI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kbli.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kbli.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kbli.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kbli.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kbli.OPGetRefKbli
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kbli", partName = "part_get_reply")
    public OPGetRefKbli get(
        @WebParam(name = "IPGetRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kbli", partName = "part_get_request")
        IPGetRefKbli partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kbli.OPInsRefKbli
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kbli", partName = "part_insert_reply")
    public OPInsRefKbli insert(
        @WebParam(name = "IPInsRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kbli", partName = "part_insert_request")
        IPInsRefKbli partInsertRequest);

    /**
     * 
     * @param partUdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kbli.OPUpdRefKbli
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kbli", partName = "part_update_reply")
    public OPUpdRefKbli update(
        @WebParam(name = "IPUpdRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kbli", partName = "part_udate_request")
        IPUpdRefKbli partUdateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kbli.OPDelRefKbli
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kbli", partName = "part_delete_reply")
    public OPDelRefKbli delete(
        @WebParam(name = "IPDelRefKbli", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kbli", partName = "part_delete_request")
        IPDelRefKbli partDeleteRequest);

}
