
package com.oracle.sca.soapservice.eproc_secman.lib_eproc.ws_library_list;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc_Secman/LIB_Eproc/WS_Library_List")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.sp_get_xml_bank.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_json_provinsi.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi_2.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.sp_simpan_bank.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param part1
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_json_provinsi.OutputParameters
     */
    @WebMethod(operationName = "get_list_Json_Provinsi", action = "get_list_Json_Provinsi")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_Json_provinsi", partName = "part1")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_json_provinsi.OutputParameters getListJsonProvinsi(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_Json_provinsi", partName = "part1")
        com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_json_provinsi.InputParameters part1);

    /**
     * 
     * @param inputXMLParameter
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi.OutputParameters
     */
    @WebMethod(operationName = "get_list_XML_Provinsi", action = "get_list_XML_Provinsi")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_XML_provinsi", partName = "OutputXMLParameter")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi.OutputParameters getListXMLProvinsi(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_XML_provinsi", partName = "InputXMLParameter")
        com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi.InputParameters inputXMLParameter);

    /**
     * 
     * @param inputXMLParameter2
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi_2.OutputParameters
     */
    @WebMethod(operationName = "get_list_XML_Provinsi2", action = "get_list_XML_Provinsi2")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_XML_Provinsi_2", partName = "OutputXMLParameter2")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi_2.OutputParameters getListXMLProvinsi2(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_list_XML_Provinsi_2", partName = "InputXMLParameter2")
        com.oracle.xmlns.pcbpel.adapter.db.sp.sp_list_xml_provinsi_2.InputParameters inputXMLParameter2);

    /**
     * 
     * @param inputParamSimpanBank
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.sp_simpan_bank.OutputParameters
     */
    @WebMethod(operationName = "insert_simpan_bank", action = "insert_simpan_bank")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_simpan_bank", partName = "OutputParamSimpanBank")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.sp_simpan_bank.OutputParameters insertSimpanBank(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_simpan_bank", partName = "InputParamSimpanBank")
        com.oracle.xmlns.pcbpel.adapter.db.sp.sp_simpan_bank.InputParameters inputParamSimpanBank);

    /**
     * 
     * @param inputParamXMLBank
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.sp_get_xml_bank.OutputParameters
     */
    @WebMethod(operationName = "get_list_XML_Bank", action = "get_list_XML_Bank")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_XML_Bank", partName = "OutputParamXMLBank")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.sp_get_xml_bank.OutputParameters getListXMLBank(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_XML_Bank", partName = "InputParamXMLBank")
        com.oracle.xmlns.pcbpel.adapter.db.sp.sp_get_xml_bank.InputParameters inputParamXMLBank);

}
