
package com.oracle.sca.soapservice.eproc_secman.eproc_secman.ws_secman_role;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc_Secman/Eproc_Secman/WS_Secman_Role")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getdaftar_by_user.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_by_user.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_id_user_clob.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_role_by_user.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getvalidasi_by_user.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.scm_validasi_user.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param part1
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_validasi_user.OutputParameters
     */
    @WebMethod(action = "getvalidasiuser")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_validasi_user", partName = "part1")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_validasi_user.OutputParameters getvalidasiuser(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_validasi_user", partName = "part1")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_validasi_user.InputParameters part1);

    /**
     * 
     * @param getMenuInputParameters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_by_user.OutputParameters
     */
    @WebMethod(operationName = "getmenu_by_user", action = "getmenu_by_user")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_menu_by_user", partName = "GetMenuOutputParameters")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_by_user.OutputParameters getmenuByUser(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_menu_by_user", partName = "GetMenuInputParameters")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_by_user.InputParameters getMenuInputParameters);

    /**
     * 
     * @param getRoleInputParameters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_role_by_user.OutputParameters
     */
    @WebMethod(operationName = "getrole_by_user", action = "getrole_by_user")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_role_by_user", partName = "GetRoleOutputParameters")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_role_by_user.OutputParameters getroleByUser(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_role_by_user", partName = "GetRoleInputParameters")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_role_by_user.InputParameters getRoleInputParameters);

    /**
     * 
     * @param getDaftarMenuInputParamaters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getdaftar_by_user.OutputParameters
     */
    @WebMethod(action = "getdafarmenu")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getdaftar_by_user", partName = "GetDaftarMenuOutputParamaters")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getdaftar_by_user.OutputParameters getdafarmenu(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getdaftar_by_user", partName = "GetDaftarMenuInputParamaters")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getdaftar_by_user.InputParameters getDaftarMenuInputParamaters);

    /**
     * 
     * @param getCLOBMenuInputParamaters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_id_user_clob.OutputParameters
     */
    @WebMethod(operationName = "get_list_menu_by_user", action = "get_list_menu_by_user")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_menu_id_user_clob", partName = "GetCLOBMenuOutputParamaters")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_id_user_clob.OutputParameters getListMenuByUser(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getlist_menu_id_user_clob", partName = "GetCLOBMenuInputParamaters")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getlist_menu_id_user_clob.InputParameters getCLOBMenuInputParamaters);

    /**
     * 
     * @param getValidasiUserInputParameters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getvalidasi_by_user.OutputParameters
     */
    @WebMethod(operationName = "get_validasi_by_user", action = "get_validasi_by_user")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getvalidasi_by_user", partName = "GetValidasiUserOutputParameters")
    public com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getvalidasi_by_user.OutputParameters getValidasiByUser(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/scm_getvalidasi_by_user", partName = "GetValidasiUserInputParameters")
        com.oracle.xmlns.pcbpel.adapter.db.sp.scm_getvalidasi_by_user.InputParameters getValidasiUserInputParameters);

}
