
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_kualifikasi_penyedia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kualifikasi_penyedia.IPDelRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kualifikasi_penyedia.OPDelRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kualifikasi_penyedia.IPGetRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kualifikasi_penyedia.OPGetRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kualifikasi_penyedia.IPInsRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kualifikasi_penyedia.OPInsRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kualifikasi_penyedia.IPUpdRefKualifikasiPenyedia;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kualifikasi_penyedia.OPUpdRefKualifikasiPenyedia;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_KUALIFIKASI_PENYEDIA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kualifikasi_penyedia.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kualifikasi_penyedia.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kualifikasi_penyedia.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kualifikasi_penyedia.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_kualifikasi_penyedia.OPGetRefKualifikasiPenyedia
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kualifikasi_penyedia", partName = "part_get_reply")
    public OPGetRefKualifikasiPenyedia get(
        @WebParam(name = "IPGetRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_kualifikasi_penyedia", partName = "part_get_request")
        IPGetRefKualifikasiPenyedia partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_kualifikasi_penyedia.OPInsRefKualifikasiPenyedia
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kualifikasi_penyedia", partName = "part_insert_reply")
    public OPInsRefKualifikasiPenyedia insert(
        @WebParam(name = "IPInsRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_kualifikasi_penyedia", partName = "part_insert_request")
        IPInsRefKualifikasiPenyedia partInsertRequest);

    /**
     * 
     * @param partUpdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_kualifikasi_penyedia.OPUpdRefKualifikasiPenyedia
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kualifikasi_penyedia", partName = "part_update_reply")
    public OPUpdRefKualifikasiPenyedia update(
        @WebParam(name = "IPUpdRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_kualifikasi_penyedia", partName = "part_update_request")
        IPUpdRefKualifikasiPenyedia partUpdateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_kualifikasi_penyedia.OPDelRefKualifikasiPenyedia
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kualifikasi_penyedia", partName = "part_delete_reply")
    public OPDelRefKualifikasiPenyedia delete(
        @WebParam(name = "IPDelRefKualifikasiPenyedia", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_kualifikasi_penyedia", partName = "part_delete_request")
        IPDelRefKualifikasiPenyedia partDeleteRequest);

}
