
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_dana;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_dana.IPDelRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_dana.OPDelRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_dana.IPGetRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_dana.OPGetRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_dana.IPInsRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_dana.OPInsRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_dana.IPUpdRefDana;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_dana.OPUpdRefDana;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_DANA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_dana.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_dana.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_dana.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_dana.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_dana.OPGetRefDana
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_dana", partName = "part_get_reply")
    public OPGetRefDana get(
        @WebParam(name = "IPGetRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_dana", partName = "part_get_request")
        IPGetRefDana partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_dana.OPInsRefDana
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_dana", partName = "part_insert_reply")
    public OPInsRefDana insert(
        @WebParam(name = "IPInsRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_dana", partName = "part_insert_request")
        IPInsRefDana partInsertRequest);

    /**
     * 
     * @param partUpdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_dana.OPUpdRefDana
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_dana", partName = "part_update_reply")
    public OPUpdRefDana update(
        @WebParam(name = "IPUpdRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_dana", partName = "part_update_request")
        IPUpdRefDana partUpdateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_dana.OPDelRefDana
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_dana", partName = "part_delete_reply")
    public OPDelRefDana delete(
        @WebParam(name = "IPDelRefDana", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_dana", partName = "part_delete_request")
        IPDelRefDana partDeleteRequest);

}
