
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_jenis_anggaran;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_jenis_anggaran.IPDelRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_jenis_anggaran.OPDelRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_jenis_anggaran.IPGetRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_jenis_anggaran.OPGetRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_jenis_anggaran.IPInsRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_jenis_anggaran.OPInsRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_jenis_anggaran.IPUpdRefJenisAnggaran;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_jenis_anggaran.OPUpdRefJenisAnggaran;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_JENIS_ANGGARAN")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_jenis_anggaran.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_jenis_anggaran.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_jenis_anggaran.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_jenis_anggaran.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_jenis_anggaran.OPGetRefJenisAnggaran
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_jenis_anggaran", partName = "part_get_reply")
    public OPGetRefJenisAnggaran get(
        @WebParam(name = "IPGetRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_jenis_anggaran", partName = "part_get_request")
        IPGetRefJenisAnggaran partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_jenis_anggaran.OPInsRefJenisAnggaran
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_jenis_anggaran", partName = "part_insert_reply")
    public OPInsRefJenisAnggaran insert(
        @WebParam(name = "IPInsRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_jenis_anggaran", partName = "part_insert_request")
        IPInsRefJenisAnggaran partInsertRequest);

    /**
     * 
     * @param partUpdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_jenis_anggaran.OPUpdRefJenisAnggaran
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_jenis_anggaran", partName = "part_update_reply")
    public OPUpdRefJenisAnggaran update(
        @WebParam(name = "IPUpdRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_jenis_anggaran", partName = "part_update_request")
        IPUpdRefJenisAnggaran partUpdateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_jenis_anggaran.OPDelRefJenisAnggaran
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_jenis_anggaran", partName = "part_delete_reply")
    public OPDelRefJenisAnggaran delete(
        @WebParam(name = "IPDelRefJenisAnggaran", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_jenis_anggaran", partName = "part_delete_request")
        IPDelRefJenisAnggaran partDeleteRequest);

}
