
package com.oracle.sca.soapservice.eprocs.soa_master.ws_master_ref_bidang;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_bidang.IPDelRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_bidang.OPDelRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_bidang.IPGetRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_bidang.OPGetRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_bidang.IPInsRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_bidang.OPInsRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_bidang.IPUpdRefBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_bidang.OPUpdRefBidang;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BIDANG")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_bidang.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param insReq
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_bidang.OPInsRefBidang
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_bidang", partName = "insRep")
    public OPInsRefBidang insert(
        @WebParam(name = "IPInsRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_bidang", partName = "insReq")
        IPInsRefBidang insReq);

    /**
     * 
     * @param updReq
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_bidang.OPUpdRefBidang
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_bidang", partName = "updRep")
    public OPUpdRefBidang update(
        @WebParam(name = "IPUpdRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_bidang", partName = "updReq")
        IPUpdRefBidang updReq);

    /**
     * 
     * @param delReq
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_bidang.OPDelRefBidang
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_bidang", partName = "delRep")
    public OPDelRefBidang delete(
        @WebParam(name = "IPDelRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_bidang", partName = "delReq")
        IPDelRefBidang delReq);

    /**
     * 
     * @param delReq
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_bidang.OPGetRefBidang
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_bidang", partName = "getRep")
    public OPGetRefBidang get(
        @WebParam(name = "IPGetRefBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_bidang", partName = "delReq")
        IPGetRefBidang delReq);

}
