
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_negara;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_negara.IPDelRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_negara.OPDelRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_negara.IPGetRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_negara.OPGetRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_negara.IPInsRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_negara.OPInsRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_negara.IPUpdRefNegara;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_negara.OPUpdRefNegara;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_NEGARA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_negara.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_negara.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_negara.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_negara.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_negara.OPGetRefNegara
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_negara", partName = "part_insert_reply")
    public OPGetRefNegara get(
        @WebParam(name = "IPGetRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_negara", partName = "part_get_request")
        IPGetRefNegara partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_negara.OPInsRefNegara
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_negara", partName = "part_insert_reply")
    public OPInsRefNegara insert(
        @WebParam(name = "IPInsRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_negara", partName = "part_insert_request")
        IPInsRefNegara partInsertRequest);

    /**
     * 
     * @param partUpdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_negara.OPUpdRefNegara
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_negara", partName = "part_update_reply")
    public OPUpdRefNegara update(
        @WebParam(name = "IPUpdRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_negara", partName = "part_update_request")
        IPUpdRefNegara partUpdateRequest);

    /**
     * 
     * @param partDelRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_negara.OPDelRefNegara
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_negara", partName = "part_delete_reply")
    public OPDelRefNegara delete(
        @WebParam(name = "IPDelRefNegara", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_negara", partName = "part_del_request")
        IPDelRefNegara partDelRequest);

}
