
package com.oracle.sca.soapservice.eprocs.soa_master.ws_master_ref_bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_MASTER_REF_BANK", targetNamespace = "http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BANK", wsdlLocation = "http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_BANK?WSDL")
public class WSMASTERREFBANK
    extends Service
{

    private final static URL WSMASTERREFBANK_WSDL_LOCATION;
    private final static WebServiceException WSMASTERREFBANK_EXCEPTION;
    private final static QName WSMASTERREFBANK_QNAME = new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BANK", "WS_MASTER_REF_BANK");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_BANK?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMASTERREFBANK_WSDL_LOCATION = url;
        WSMASTERREFBANK_EXCEPTION = e;
    }

    public WSMASTERREFBANK() {
        super(__getWsdlLocation(), WSMASTERREFBANK_QNAME);
    }

    public WSMASTERREFBANK(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMASTERREFBANK_QNAME, features);
    }

    public WSMASTERREFBANK(URL wsdlLocation) {
        super(wsdlLocation, WSMASTERREFBANK_QNAME);
    }

    public WSMASTERREFBANK(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMASTERREFBANK_QNAME, features);
    }

    public WSMASTERREFBANK(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMASTERREFBANK(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt() {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BANK", "execute_pt"), ExecutePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BANK", "execute_pt"), ExecutePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMASTERREFBANK_EXCEPTION!= null) {
            throw WSMASTERREFBANK_EXCEPTION;
        }
        return WSMASTERREFBANK_WSDL_LOCATION;
    }

}
