
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_sub_bidang;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_sub_bidang.IPDelRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_sub_bidang.OPDelRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_sub_bidang.IPGetRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_sub_bidang.OPGetRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_sub_bidang.IPInsRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_sub_bidang.OPInsRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_sub_bidang.IPUpdRefSubBidang;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_sub_bidang.OPUpdRefSubBidang;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_SUB_BIDANG")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_sub_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_sub_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_sub_bidang.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_sub_bidang.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param partGetRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_sub_bidang.OPGetRefSubBidang
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_sub_bidang", partName = "part_get_reply")
    public OPGetRefSubBidang get(
        @WebParam(name = "IPGetRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_sub_bidang", partName = "part_get_request")
        IPGetRefSubBidang partGetRequest);

    /**
     * 
     * @param partInsertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_sub_bidang.OPInsRefSubBidang
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_sub_bidang", partName = "part_insert_reply")
    public OPInsRefSubBidang insert(
        @WebParam(name = "IPInsRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_sub_bidang", partName = "part_insert_request")
        IPInsRefSubBidang partInsertRequest);

    /**
     * 
     * @param partUpdateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_sub_bidang.OPUpdRefSubBidang
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_sub_bidang", partName = "part_update_reply")
    public OPUpdRefSubBidang update(
        @WebParam(name = "IPUpdRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_sub_bidang", partName = "part_update_request")
        IPUpdRefSubBidang partUpdateRequest);

    /**
     * 
     * @param partDeleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_sub_bidang.OPDelRefSubBidang
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_sub_bidang", partName = "part_delete_reply")
    public OPDelRefSubBidang delete(
        @WebParam(name = "IPDelRefSubBidang", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_sub_bidang", partName = "part_delete_request")
        IPDelRefSubBidang partDeleteRequest);

}
