
package com.oracle.sca.soapservice.eproc.soa_master.ws_master_ref_sub_bidang;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_MASTER_REF_SUB_BIDANG", targetNamespace = "http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_SUB_BIDANG", wsdlLocation = "http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_SUB_BIDANG?WSDL")
public class WSMASTERREFSUBBIDANG
    extends Service
{

    private final static URL WSMASTERREFSUBBIDANG_WSDL_LOCATION;
    private final static WebServiceException WSMASTERREFSUBBIDANG_EXCEPTION;
    private final static QName WSMASTERREFSUBBIDANG_QNAME = new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_SUB_BIDANG", "WS_MASTER_REF_SUB_BIDANG");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_SUB_BIDANG?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMASTERREFSUBBIDANG_WSDL_LOCATION = url;
        WSMASTERREFSUBBIDANG_EXCEPTION = e;
    }

    public WSMASTERREFSUBBIDANG() {
        super(__getWsdlLocation(), WSMASTERREFSUBBIDANG_QNAME);
    }

    public WSMASTERREFSUBBIDANG(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMASTERREFSUBBIDANG_QNAME, features);
    }

    public WSMASTERREFSUBBIDANG(URL wsdlLocation) {
        super(wsdlLocation, WSMASTERREFSUBBIDANG_QNAME);
    }

    public WSMASTERREFSUBBIDANG(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMASTERREFSUBBIDANG_QNAME, features);
    }

    public WSMASTERREFSUBBIDANG(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMASTERREFSUBBIDANG(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt() {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_SUB_BIDANG", "execute_pt"), ExecutePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eproc/SOA_Master/WS_MASTER_REF_SUB_BIDANG", "execute_pt"), ExecutePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMASTERREFSUBBIDANG_EXCEPTION!= null) {
            throw WSMASTERREFSUBBIDANG_EXCEPTION;
        }
        return WSMASTERREFSUBBIDANG_WSDL_LOCATION;
    }

}
