
package com.oracle.sca.soapservice.eprocs.soa_master.ws_master_ref_badan_usaha;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_badan_usaha.IPDelRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_badan_usaha.OPDelRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_badan_usaha.IPGetRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_badan_usaha.OPGetRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_badan_usaha.IPInsRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_badan_usaha.OPInsRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_badan_usaha.IPUpdRefBadanUsaha;
import com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_badan_usaha.OPUpdRefBadanUsaha;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BADAN_USAHA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_badan_usaha.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_badan_usaha.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_badan_usaha.ObjectFactory.class,
    com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_badan_usaha.ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param updateRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_upd_ref_badan_usaha.OPUpdRefBadanUsaha
     */
    @WebMethod(action = "update")
    @WebResult(name = "OPUpdRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_badan_usaha", partName = "updateReply")
    public OPUpdRefBadanUsaha update(
        @WebParam(name = "IPUpdRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_upd_ref_badan_usaha", partName = "updateRequest")
        IPUpdRefBadanUsaha updateRequest);

    /**
     * 
     * @param deleteRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_del_ref_badan_usaha.OPDelRefBadanUsaha
     */
    @WebMethod(action = "delete")
    @WebResult(name = "OPDelRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_badan_usaha", partName = "deleteReply")
    public OPDelRefBadanUsaha delete(
        @WebParam(name = "IPDelRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_del_ref_badan_usaha", partName = "deleteRequest")
        IPDelRefBadanUsaha deleteRequest);

    /**
     * 
     * @param insertRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_ins_ref_badan_usaha.OPInsRefBadanUsaha
     */
    @WebMethod(action = "insert")
    @WebResult(name = "OPInsRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_badan_usaha", partName = "insertReply")
    public OPInsRefBadanUsaha insert(
        @WebParam(name = "IPInsRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_ins_ref_badan_usaha", partName = "insertRequest")
        IPInsRefBadanUsaha insertRequest);

    /**
     * 
     * @param getRequest
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.pkg_master_get_ref_badan_usaha.OPGetRefBadanUsaha
     */
    @WebMethod(action = "get")
    @WebResult(name = "OPGetRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_badan_usaha", partName = "getReply")
    public OPGetRefBadanUsaha get(
        @WebParam(name = "IPGetRefBadanUsaha", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/pkg_master_get_ref_badan_usaha", partName = "getRequest")
        IPGetRefBadanUsaha getRequest);

}
