
package com.oracle.sca.soapservice.eprocs.soa_master.ws_master_ref_badan_usaha;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_MASTER_REF_BADAN_USAHA", targetNamespace = "http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BADAN_USAHA", wsdlLocation = "http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_BADAN_USAHA?WSDL")
public class WSMASTERREFBADANUSAHA
    extends Service
{

    private final static URL WSMASTERREFBADANUSAHA_WSDL_LOCATION;
    private final static WebServiceException WSMASTERREFBADANUSAHA_EXCEPTION;
    private final static QName WSMASTERREFBADANUSAHA_QNAME = new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BADAN_USAHA", "WS_MASTER_REF_BADAN_USAHA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.69.203:8001/soa-infra/services/latihan/SOA_Master/WS_MASTER_REF_BADAN_USAHA?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMASTERREFBADANUSAHA_WSDL_LOCATION = url;
        WSMASTERREFBADANUSAHA_EXCEPTION = e;
    }

    public WSMASTERREFBADANUSAHA() {
        super(__getWsdlLocation(), WSMASTERREFBADANUSAHA_QNAME);
    }

    public WSMASTERREFBADANUSAHA(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMASTERREFBADANUSAHA_QNAME, features);
    }

    public WSMASTERREFBADANUSAHA(URL wsdlLocation) {
        super(wsdlLocation, WSMASTERREFBADANUSAHA_QNAME);
    }

    public WSMASTERREFBADANUSAHA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMASTERREFBADANUSAHA_QNAME, features);
    }

    public WSMASTERREFBADANUSAHA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMASTERREFBADANUSAHA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt() {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BADAN_USAHA", "execute_pt"), ExecutePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_pt")
    public ExecutePtt getExecutePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/Eprocs/SOA_Master/WS_MASTER_REF_BADAN_USAHA", "execute_pt"), ExecutePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMASTERREFBADANUSAHA_EXCEPTION!= null) {
            throw WSMASTERREFBADANUSAHA_EXCEPTION;
        }
        return WSMASTERREFBADANUSAHA_WSDL_LOCATION;
    }

}
